#!/usr/bin/env bash
#scripts for installing nginx

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'
echo 'Hello World!' | sudo tree /var/www/html/index.html

sudo nginx -t
sudo service nginx reload
