#!/usr/bin/env bash
#scripts for installing nginx

#update packages
sudo apt-get update -y -qq
sudo apt-get install nginx -y

sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckupfile

echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://cuberule.com/;
    }
}" > /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart

echo -e "\n Done!\n"
