#!/usr/bin/env bash
# Scripts for redirecting page to 404 page and configuring custom HTTP response header

# Update package list and install Nginx
sudo apt-get update -y -qq
sudo apt-get install nginx -y

# Start Nginx service
sudo service nginx start

# Allow Nginx HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Set ownership and permissions for web directories
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckupfile

# Create a custom 404 page
echo -e "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By \$hostname;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx to apply changes
sudo service nginx restart

echo -e "\ndone\n"
