#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server web-01 515924-web-01:80 check
    server web-02 515924-web-02:80 check
EOF

# Start HAProxy service
sudo systemctl start haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

echo "HAProxy success config"
