#!/usr/bin/env bash
# This script is displaying "Best School" 10 times,on 9 print hi
i=1
while((i<11))
do
	echo "Best School"
	if((i==9))
	then 
		#echo "Best School"
		echo "Hi"
	fi
	#echo "Best School"
	((i++))
done
