#!/usr/bin/env bash
#display information

fname="School"

if [ -e $fname ]
then
    echo "School file exists"
    if [ -s $fname ]
    then
        echo "School file is not empty"
    else
        echo "School file is empty"
    fi
    if [ -f $fname ]
    then
        echo "School is a regular file"
    fi
else
    echo "School file does not exist"
fi
